# pyright: basic
"""Keyword and TriggerCondition enums for the parser AST.

These are open-ended enums; consumers that don't recognise a member should
emit their own gap error rather than crashing.
"""
from __future__ import annotations

from enum import Enum


class Keyword(Enum):
    """Keyword abilities recognised by the parser."""

    # Evergreen
    FLYING = "flying"
    TRAMPLE = "trample"
    FIRST_STRIKE = "first strike"
    DOUBLE_STRIKE = "double strike"
    DEATHTOUCH = "deathtouch"
    LIFELINK = "lifelink"
    HASTE = "haste"
    VIGILANCE = "vigilance"
    REACH = "reach"
    MENACE = "menace"
    HEXPROOF = "hexproof"
    SHROUD = "shroud"
    INDESTRUCTIBLE = "indestructible"
    FLASH = "flash"
    DEFENDER = "defender"
    # Older / less common
    INTIMIDATE = "intimidate"
    FEAR = "fear"
    SHADOW = "shadow"
    HORSEMANSHIP = "horsemanship"
    PROWESS = "prowess"
    CHANGELING = "changeling"
    # Parametric (carry a `parameter: str | None` on KeywordAbility)
    EQUIP = "equip"
    WARD = "ward"
    PROTECTION = "protection"
    LANDWALK = "landwalk"
    CYCLING = "cycling"
    KICKER = "kicker"
    FLASHBACK = "flashback"
    BUYBACK = "buyback"
    ENCHANT = "enchant"
    BANDING = "banding"
    RAMPAGE = "rampage"
    BUSHIDO = "bushido"
    ANNIHILATOR = "annihilator"
    FADING = "fading"
    VANISHING = "vanishing"
    SUSPEND = "suspend"
    MORPH = "morph"
    AMPLIFY = "amplify"
    MODULAR = "modular"
    AFFINITY = "affinity"
    SOULSHIFT = "soulshift"
    DREDGE = "dredge"
    BLOODTHIRST = "bloodthirst"
    GRAFT = "graft"
    POISONOUS = "poisonous"
    DEVOUR = "devour"
    NINJUTSU = "ninjutsu"
    TRANSMUTE = "transmute"
    REPLICATE = "replicate"
    RECOVER = "recover"
    SPLICE = "splice"
    OFFERING = "offering"
    CHAMPION = "champion"
    EVOKE = "evoke"
    PROWL = "prowl"
    REINFORCE = "reinforce"
    UNEARTH = "unearth"
    LEVEL_UP = "level up"
    MIRACLE = "miracle"
    OVERLOAD = "overload"
    SCAVENGE = "scavenge"
    BESTOW = "bestow"
    OUTLAST = "outlast"
    DASH = "dash"
    AWAKEN = "awaken"
    SURGE = "surge"
    EMERGE = "emerge"
    ESCALATE = "escalate"
    CREW = "crew"
    FABRICATE = "fabricate"
    PARTNER = "partner"
    EMBALM = "embalm"
    ETERNALIZE = "eternalize"
    AFFLICT = "afflict"
    SURVEIL = "surveil"
    JUMP_START = "jump-start"
    FORTIFY = "fortify"
    ENTWINE = "entwine"
    MADNESS = "madness"
    MULTIKICKER = "multikicker"
    CASCADE = "cascade"
    STORM = "storm"
    SUNBURST = "sunburst"
    CONVOKE = "convoke"
    DELVE = "delve"
    GRAVESTORM = "gravestorm"
    REBOUND = "rebound"
    TOTEM_ARMOR = "totem armor"
    INFECT = "infect"
    BATTLE_CRY = "battle cry"
    LIVING_WEAPON = "living weapon"
    UNDYING = "undying"
    SOULBOND = "soulbond"
    UNLEASH = "unleash"
    CIPHER = "cipher"
    EVOLVE = "evolve"
    EXTORT = "extort"
    FUSE = "fuse"
    DETHRONE = "dethrone"
    EXPLOIT = "exploit"
    DEVOID = "devoid"
    INGEST = "ingest"
    MYRIAD = "myriad"
    SKULK = "skulk"
    MELEE = "melee"
    IMPROVISE = "improvise"
    AFTERMATH = "aftermath"
    ASCEND = "ascend"
    ASSIST = "assist"
    MENTOR = "mentor"
    HIDEAWAY = "hideaway"
    CONSPIRE = "conspire"
    PERSIST = "persist"
    WITHER = "wither"
    RETRACE = "retrace"
    EXALTED = "exalted"
    PROVOKE = "provoke"
    EPIC = "epic"
    HAUNT = "haunt"
    ABSORB = "absorb"
    FRENZY = "frenzy"
    TRANSFIGURE = "transfigure"
    AURA_SWAP = "aura swap"
    ECHO = "echo"
    SPLIT_SECOND = "split second"
    RIPPLE = "ripple"
    HIDDEN_AGENDA = "hidden agenda"
    DOUBLE_AGENDA = "double agenda"
    RENOWN = "renown"
    TRIBUTE = "tribute"
    FORECAST = "forecast"
    CUMULATIVE_UPKEEP = "cumulative upkeep"
    PHASING = "phasing"


class TriggerCondition(Enum):
    """Trigger conditions for triggered abilities. Open-ended."""

    ENTERS_BATTLEFIELD = "enters"
    LEAVES_BATTLEFIELD = "leaves"
    ATTACKS = "attacks"
    BLOCKS = "blocks"
    DIES = "dies"
    CAST_SPELL = "cast_spell"
    BEGINNING_OF_UPKEEP = "upkeep"
    BEGINNING_OF_DRAW = "draw_step"
    BEGINNING_OF_COMBAT = "beginning_of_combat"
    END_OF_COMBAT = "end_of_combat"
    BEGINNING_OF_END_STEP = "end_step"
    END_OF_TURN = "end_of_turn"
