# pyright: basic
"""Unmodeled-rule playbook driver: orchestrate U0-U9.

Public entry point: :func:`run`. The driver runs:

* U0 — read the rule definition from ``grammar.py`` (orchestrator).
* U1 — list existing AST dataclasses per parent module (orchestrator).
* U2 — git log for recent ``parser: handle <X>`` commits + diffs (orchestrator).
* U2b — heuristic: pick parent module by suffix (could-move).
* U3 — LLM designs the AST dataclass.
* U4 — LLM writes the transformer method body.
* U5 — orchestrator writes the AST file, updates __init__.py, appends the
  method (all via libcst).
* U6 — pytest gate.
* U8/U9 — diagnose + revise + reapply on a red retry.

See ``experiments/playbook-design.html`` section 2c for the full DAG.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import Any, Callable

from . import PlaybookResult, context, driver as _driver_mod, edits, heuristics, llm, log_step
from .lower import L4_MODEL, L5_MODEL, L9_MODEL, _call, _short, run_pytest


# ---------------------------------------------------------------------------
# Live-card classify gate (U6b / U6b-retry)
# ---------------------------------------------------------------------------
#
# Mirror of the lower playbook's L7b gate. pytest accepts a new AST class +
# transformer method even when the method doesn't actually consume the
# specific shape the live card emits — the transformer's __default__ then
# raises LoweringIncomplete and surfaces the SAME unmodeled-rule:X label
# on the next iteration. The gate re-parses the originating card in a
# fresh subprocess (the playbook just edited transformer.py + the AST
# package, so in-process imports are stale) and reverts U5's edits if
# the same label re-fires.


def _live_card_still_failing_unmodeled(
    *, card_name: str, oracle_text: str, label: str
) -> bool:
    """True iff a fresh parse of ``card_name`` returns ``label`` again.

    Returns False on subprocess errors too here — unlike the lower
    playbook's gate. Reason: U5's edits touch three files (a new AST
    module member, parser/ast/__init__.py, parser/transformer.py); a
    subprocess crash post-edit usually means the new code itself is
    broken, which pytest already caught. Crashes that survive pytest
    are extremely rare; reverting on them risks blocking real progress.
    """
    if not card_name or not oracle_text:
        return False
    probe = (
        "import json, sys\n"
        "from argentum_press.parser import parse\n"
        f"r = parse({oracle_text!r}, name={card_name!r})\n"
        "if r.ok or r.error is None:\n"
        "    print(json.dumps({'result': 'ok'}))\n"
        "    sys.exit(0)\n"
        "print(json.dumps({'result': 'error', 'message': r.error.message}))\n"
    )
    proc = subprocess.run(
        [sys.executable, "-c", probe],
        cwd=context.REPO,
        capture_output=True,
        text=True,
        check=False,
        env={**os.environ},
    )
    if proc.returncode != 0:
        return False
    try:
        out = json.loads(proc.stdout.strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError):
        return False
    if out["result"] == "ok":
        return False
    return out.get("message") == label


U3_MODEL = L4_MODEL
U4_MODEL = L5_MODEL
U8_MODEL = L9_MODEL


def _resolve_models(override: str | None) -> tuple[str, str, str]:
    if override:
        return override, override, override
    return U3_MODEL, U4_MODEL, U8_MODEL


def _format_module_summary(mod: context.AstModuleSummary) -> str:
    """Short class-list dump for the U3 prompt."""
    lines = [f"# {mod.module}.py — {len(mod.class_names)} classes"]
    for name in mod.class_names:
        lines.append(f"  - {name}")
    return "\n".join(lines)


def _format_exemplars(exemplars: list[context.TransformerExemplar]) -> str:
    parts = []
    for ex in exemplars:
        parts.append(f"# commit {ex.commit} — rule {ex.rule_name}\n\n{ex.diff}")
    return "\n\n---\n\n".join(parts) if parts else "(no exemplars found)"


def _ast_class_source_from_design(design: dict[str, Any]) -> str:
    """Render the U3 design dict into Python source for the new dataclass."""
    classname = design["classname"]
    parent = design["parent_class"]
    docstring = design["docstring"].strip() or f"{classname} — generated by playbook."
    field_lines: list[str] = []
    for f in design["fields"]:
        anno = f["type"]
        default = f.get("default")
        if default is None:
            field_lines.append(f"    {f['name']}: {anno}")
        else:
            field_lines.append(f"    {f['name']}: {anno} = {default}")
    body = "\n".join(field_lines) if field_lines else "    pass"
    docstring_block = f'    """{docstring}"""'
    return (
        "@dataclass(frozen=True, slots=True)\n"
        f"class {classname}({parent}):\n"
        f"{docstring_block}\n\n"
        f"{body}\n"
    )


def _u3_user_prompt(rule_name: str, parent_module: str, suffix_conf: float) -> str:
    return (
        f"Design the AST dataclass for the unmodeled grammar rule {rule_name!r}. "
        f"Suggested parent_module={parent_module!r} (suffix heuristic, "
        f"confidence={suffix_conf:.2f}). Override only if the rule is clearly "
        f"misclassified. Pick a parent_class from the existing classes in that "
        f"file. Field types use the project's idioms: tuple[X, ...] for "
        f"collections, X | None for optionals, str/int for literals. Provide a "
        f"one-line docstring. Return JSON exactly as the schema specifies."
    )


def _u4_user_prompt(rule_name: str) -> str:
    return (
        f"Write the CardTransformer method body for {rule_name!r}. Header should "
        f"be `def {rule_name}(self, items):`. Inspect `items` types to pick the "
        f"right fields out; the children are already transformed (no lark Tree "
        f"objects). Use isinstance() checks against the existing AST classes. "
        f"List any AST class names you reference in extra_imports (the orchestrator "
        f"adds them to the transformer's `from argentum_press.parser.ast import (...)` "
        f"block automatically; the dataclass you just designed is added without "
        f"needing to mention it). Don't include @v_args — none of the existing "
        f"methods use it."
    )


def run(
    *,
    label: str,
    project_dir: Path,
    repo: Path | None = None,
    client: llm.ClientLike | None = None,
    pool: _driver_mod.DriverPool | None = None,
    pytest_runner: Callable[[Path], tuple[int, str]] | None = None,
    card_name: str = "",
    oracle_text: str = "",
    verbose: bool = True,
    model_override: str | None = None,
) -> PlaybookResult:
    """End-to-end unmodeled-rule playbook.

    Returns a :class:`PlaybookResult` with the step trace; never raises.
    Outcomes encode the failure mode (``aborted-u0``, ``aborted-u3``,
    ``aborted-u5``, ``aborted-retry-pytest``, etc.).
    """
    repo = repo or context.REPO
    pytest_runner = pytest_runner or run_pytest
    u3_model, u4_model, u8_model = _resolve_models(model_override)
    steps: list[Any] = []
    result = PlaybookResult(label=label, outcome="pending")

    def _say(msg: str) -> None:
        if verbose:
            print(msg, flush=True)

    # ---- U0/U1/U2: context gather ---------------------------------------
    t0 = time.monotonic()
    ctx = context.gather_unmodeled_rule(
        label=label,
        project_dir=project_dir,
        oracle_text=oracle_text,
        card_name=card_name,
    )
    if ctx.rule is None:
        result.outcome = "aborted-u0"
        log_step(
            steps, "U0", "orch", t0,
            error=f"rule {ctx.rule_name!r} not found in grammar.py",
        )
        result.steps = steps
        return result
    log_step(
        steps, "U0+U1+U2", "orch", t0,
        rule_name=ctx.rule_name,
        rule_lines=f"{ctx.rule.start_line}-{ctx.rule.end_line}",
        ast_modules=[m.module for m in ctx.ast_modules],
        exemplar_rules=[e.rule_name for e in ctx.exemplars],
    )
    _say(
        f"U0+U1+U2: rule {ctx.rule_name!r} lines {ctx.rule.start_line}-"
        f"{ctx.rule.end_line}, {len(ctx.exemplars)} exemplars"
    )

    # ---- U2b: pick parent module ----------------------------------------
    t0 = time.monotonic()
    module_choice = heuristics.pick_parent_module(ctx.rule_name)
    log_step(
        steps, "U2b", "heuristic", t0,
        module=module_choice.module,
        confidence=module_choice.confidence,
        rationale=module_choice.rationale,
    )
    _say(
        f"U2b (heuristic): parent_module={module_choice.module} "
        f"(confidence={module_choice.confidence:.2f})"
    )

    parent_module_summary = next(
        (m for m in ctx.ast_modules if m.module == module_choice.module),
        None,
    )
    if parent_module_summary is None:
        result.outcome = "aborted-u2b"
        log_step(
            steps, "U2b-validate", "orch", time.monotonic(),
            error=f"parent module {module_choice.module!r} not found in {[m.module for m in ctx.ast_modules]}",
        )
        result.steps = steps
        return result

    rule_block = context.dump_rule_definitions([ctx.rule])
    parent_module_text = _format_module_summary(parent_module_summary)
    exemplar_text = _format_exemplars(ctx.exemplars)

    # ---- U3: design the AST dataclass -----------------------------------
    t0 = time.monotonic()
    design_blocks = llm.build_ast_design_blocks(
        rule_def=rule_block,
        parent_module_summary=parent_module_text,
        exemplar_diffs=exemplar_text,
    )
    try:
        design_call = _call(
            tool_name="emit_ast_class_design",
            system_prompt=llm.UNMODELED_RULE_SYSTEM_PROMPT,
            static_context_blocks=design_blocks,
            user_prompt=_u3_user_prompt(
                ctx.rule_name, module_choice.module, module_choice.confidence
            ),
            model=u3_model,
            max_tokens=1024,
            pool=pool,
            client=client,
        )
    except Exception as e:  # noqa: BLE001
        result.outcome = "aborted-u3"
        log_step(steps, "U3", "llm", t0, error=str(e))
        result.steps = steps
        return result
    design = design_call.arguments
    log_step(steps, "U3", "llm", t0, design=design)
    _say(
        f"U3 (LLM): classname={design['classname']} parent={design['parent_class']} "
        f"fields={len(design['fields'])}"
    )

    design_json = json.dumps(design, indent=2)

    # ---- U4: write transformer method body ------------------------------
    t0 = time.monotonic()
    method_blocks = llm.build_transformer_method_blocks(
        rule_def=rule_block,
        ast_design_json=design_json,
        exemplar_diffs=exemplar_text,
    )
    try:
        method_call = _call(
            tool_name="emit_transformer_method",
            system_prompt=llm.UNMODELED_RULE_SYSTEM_PROMPT,
            static_context_blocks=method_blocks,
            user_prompt=_u4_user_prompt(ctx.rule_name),
            model=u4_model,
            max_tokens=2048,
            pool=pool,
            client=client,
        )
    except Exception as e:  # noqa: BLE001
        result.outcome = "aborted-u4"
        log_step(steps, "U4", "llm", t0, error=str(e))
        result.steps = steps
        return result
    method = method_call.arguments
    log_step(steps, "U4", "llm", t0, method=method)
    _say(f"U4 (LLM): extra_imports={method['extra_imports']}")

    plan = {"design": design, "method": method, "parent_module": module_choice.module}
    result.final_plan = plan

    # ---- U5: apply edits ------------------------------------------------
    t0 = time.monotonic()
    ast_class_source = _ast_class_source_from_design(design)
    try:
        edit = edits.apply_unmodeled_rule(
            ast_dir=context.AST_DIR,
            ast_init_path=context.AST_INIT,
            transformer_path=context.TRANSFORMER,
            parent_module=design.get("parent_module") or module_choice.module,
            classname=design["classname"],
            ast_class_source=ast_class_source,
            transformer_method_source=method["method_source"],
            extra_imports=method.get("extra_imports", []),
        )
    except edits.AnchorNotFoundError as e:
        result.outcome = "aborted-u5"
        log_step(steps, "U5", "orch", t0, error=str(e))
        result.steps = steps
        return result
    log_step(
        steps, "U5", "orch", t0,
        paths=[str(p.relative_to(repo)) for p in edit.paths],
    )
    _say(f"U5: applied edits to {len(edit.paths)} files")
    result.edit_path = ", ".join(str(p.relative_to(repo)) for p in edit.paths)

    # ---- U6: pytest -----------------------------------------------------
    t0 = time.monotonic()
    rc, out = pytest_runner(repo)
    tail = out[-1500:]
    result.pytest_first_tail = tail
    log_step(steps, "U6", "orch", t0, returncode=rc, tail=_short(tail, 200))
    _say(f"U6: pytest rc={rc}")
    if rc == 0:
        # ---- U6b: live-card classify gate ------------------------------
        # pytest accepts a transformer method that doesn't actually
        # construct the new AST class for the live card's shape — the
        # transformer's __default__ then re-raises LoweringIncomplete and
        # the same unmodeled-rule:X label re-fires on the next iteration.
        # The gate catches this before commit.
        t0 = time.monotonic()
        live_failed = _live_card_still_failing_unmodeled(
            card_name=card_name, oracle_text=oracle_text, label=label,
        )
        log_step(
            steps, "U6b", "orch", t0,
            card_name=card_name, label=label, still_failing=live_failed,
        )
        _say(f"U6b: live-card classify still_failing={live_failed}")
        if live_failed:
            edits.revert_unmodeled_rule(edit)
            result.outcome = "aborted-classify-unchanged"
            result.steps = steps
            return result
        result.outcome = "applied"
        result.steps = steps
        return result

    # ---- U8: diagnose + revise -----------------------------------------
    t0 = time.monotonic()
    retry_blocks = llm.build_unmodeled_retry_blocks(
        rule_def=rule_block,
        ast_design_json=design_json,
        method_source=method["method_source"],
        exemplar_diffs=exemplar_text,
        pytest_tail=tail,
    )
    retry_user = (
        "The previous plan failed pytest. Emit a revised transformer method "
        "(same emit_transformer_method schema). If the AST design itself was "
        "wrong (wrong fields / wrong parent class), still emit a method — the "
        "method should compensate, since the orchestrator only re-runs U4/U5 "
        "for the retry pass."
    )
    try:
        retry_call = _call(
            tool_name="emit_transformer_method",
            system_prompt=llm.UNMODELED_RULE_SYSTEM_PROMPT,
            static_context_blocks=retry_blocks,
            user_prompt=retry_user,
            model=u8_model,
            max_tokens=2048,
            pool=pool,
            client=client,
        )
    except Exception as e:  # noqa: BLE001
        edits.revert_unmodeled_rule(edit)
        result.outcome = "aborted-u8"
        log_step(steps, "U8", "llm", t0, error=str(e))
        result.steps = steps
        return result
    revised = retry_call.arguments
    log_step(steps, "U8", "llm", t0, method=revised)
    _say(f"U8 (LLM): revised method extra_imports={revised['extra_imports']}")

    # ---- U9: revert + reapply ------------------------------------------
    t0 = time.monotonic()
    edits.revert_unmodeled_rule(edit)
    try:
        edit = edits.apply_unmodeled_rule(
            ast_dir=context.AST_DIR,
            ast_init_path=context.AST_INIT,
            transformer_path=context.TRANSFORMER,
            parent_module=design.get("parent_module") or module_choice.module,
            classname=design["classname"],
            ast_class_source=ast_class_source,
            transformer_method_source=revised["method_source"],
            extra_imports=revised.get("extra_imports", []),
        )
    except edits.AnchorNotFoundError as e:
        result.outcome = "aborted-u9"
        result.final_plan = {"design": design, "method": revised}
        log_step(steps, "U9", "orch", t0, error=str(e))
        result.steps = steps
        return result
    log_step(steps, "U9", "orch", t0)
    _say("U9: reapplied revised plan")

    # ---- second pytest --------------------------------------------------
    t0 = time.monotonic()
    rc2, out2 = pytest_runner(repo)
    tail2 = out2[-1500:]
    result.pytest_retry_tail = tail2
    log_step(steps, "U6-retry", "orch", t0, returncode=rc2, tail=_short(tail2, 200))
    _say(f"U6-retry: pytest rc={rc2}")
    if rc2 == 0:
        t0 = time.monotonic()
        live_failed2 = _live_card_still_failing_unmodeled(
            card_name=card_name, oracle_text=oracle_text, label=label,
        )
        log_step(
            steps, "U6b-retry", "orch", t0,
            card_name=card_name, label=label, still_failing=live_failed2,
        )
        _say(f"U6b-retry: live-card classify still_failing={live_failed2}")
        if live_failed2:
            edits.revert_unmodeled_rule(edit)
            result.outcome = "aborted-classify-unchanged"
            result.final_plan = {"design": design, "method": revised}
            result.steps = steps
            return result
        result.outcome = "applied-after-retry"
        result.final_plan = {"design": design, "method": revised}
        result.steps = steps
        return result
    edits.revert_unmodeled_rule(edit)
    result.outcome = "aborted-retry-pytest"
    result.final_plan = {"design": design, "method": revised}
    result.steps = steps
    return result


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    import argparse
    p = argparse.ArgumentParser(description="Run the unmodeled-rule playbook for one label.")
    p.add_argument("--label", required=True, help="e.g. unmodeled-rule:colorandexpr")
    p.add_argument("--project-dir", required=True, type=Path)
    p.add_argument("--card-name", default="")
    p.add_argument("--oracle-text", default="")
    p.add_argument("--trace-out", type=Path, default=None)
    p.add_argument("--model-override", default=None)
    args = p.parse_args(argv)

    os.environ.setdefault(
        "ARGENTUM_PARSE_CACHE_DIR", str(context.REPO / ".parse-cache"),
    )

    result = run(
        label=args.label,
        project_dir=args.project_dir,
        card_name=args.card_name,
        oracle_text=args.oracle_text,
        model_override=args.model_override,
    )
    print()
    print(f"=== outcome: {result.outcome} ===")
    if result.final_plan is not None:
        print()
        print("FINAL PLAN:")
        print(json.dumps(result.final_plan, indent=2))
    if args.trace_out is not None:
        args.trace_out.parent.mkdir(parents=True, exist_ok=True)
        args.trace_out.write_text(result.as_json(), encoding="utf-8")
        print(f"trace written to {args.trace_out}")
    return 0 if result.outcome.startswith("applied") else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
